import { categoriesDef, colorsDef, sizesDef } from "./SubmissionTypes";

export const colorsInit: { [key in colorsDef]: boolean } = {
	black: false,
	white: false,
	gray: false,
	brown: false,
	red: false,
	orange: false,
	yellow: false,
	lime: false,
	green: false,
	emerald: false,
	teal: false,
	cyan: false,
	sky: false,
	blue: false,
	indigo: false,
	purple: false,
	fuchsia: false,
	pink: false,
};

export const sizesInit: { [key in sizesDef]: boolean } = {
	33: false,
	34: false,
	35: false,
	36: false,
	37: false,
	38: false,
	39: false,
	40: false,
	41: false,
	42: false,
	43: false,
	44: false,
	45: false,
	46: false,
	47: false,
	48: false,
	49: false,
	50: false,
	"4XL": false,
	"3XL": false,
	"2XL": false,
	'XL': false,
	'L': false,
	'M': false,
	'S': false,
	'XS': false,
	'XXS': false,
};
export const categoriesInit: { [key in categoriesDef]: boolean } = {
	Men: false,
	Women: false,
	Children: false,
	Sweatshirts: false,
	Sweaters: false,
	Trousers: false,
	Shorts: false,
	Shirts: false,
	Shoes: false,
};
export const detailsInit = {
	pn: "",
	bn: "",
	ip: 0,
	fp: 0,
};

export const uploadInitialState = {
	fullImages: [""],
	uploadImages: [],
	productName: "",
	brandName: "",
	colorOptions: colorsInit,
	sizeOptions: sizesInit,
	categories: categoriesInit,
	initialPrice: 0,
	finalPrice: 0,
};
